nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin:
      [
        "%env(CORS_ALLOW_ORIGIN)%",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://compare-price-api.test",
        "https://d605front.nitramlinda.fr",
        "https://www.d605front.nitramlinda.fr",
        "https://www.apps.compare.nitramlinda.fr",
        "https://apps.compare.nitramlinda.fr",
      ]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/": ~
